### ISSUE TITLE
No web cam

### ISSUE THREAD

**Issue by Kmoran1512** [lmtaek/pitchposition#1]
Unfortunately, I do not have access to a webcam currently, and without a webcam your project does not work. you might want to have some kind of default file, so that a user could use the website without a webcam needed. Also if you go through your website with only a screen reader I was unable to find the directions to turn on my webcam regardless of not having one, so if a user is visually impaired they may not be able to turn on their webcam in the first place (I am using ChromeVox to test).

**Comment by lmtaek** [comment]
Thanks for the heads-up! 

Due to the nature of the project and its overall purpose (encouraging movement and activity from the user by allowing them to get feedback based on how they move), having a webcam is a necessary component—there's unfortunately not a good roundabout for accomplishing the project's goal if there's no webcam, though I appreciate your suggestions. I'll add in a disclaimer for now.

If your computer is lacking a webcam, it's possible that you won't receive any of the notifications a user with a webcam would receive—but I'm not positive of that. It's probably safest for me to double-check. I've been testing the accessibility features through VoiceOver; I'll go ahead and try to do it through your suggested screenreader, and make changes accordingly.

**Comment by Kmoran1512** [comment]
Thank you so much, I just tested using NVDA as well it looks like NVDA has a problem reading alerts too, but I can read the text on the page, so it should work okay. Also I was able to grap a computer with a webcam and test it out, looks good!
