### ISSUE TITLE
Starting Game

### ISSUE THREAD

**Issue by zlintz14** [lmtaek/pitchposition#2]
Overall, this is a really cool idea and works really well! My only comment is, if this game is for visually impaired people, how would they initially give the game access to their webcam? And also, maybe I'm not seeing it, but there didn't appear to be a way to select the start and stop buttons without clicking on them. I'm not sure how feasible it is for allowing access to the webcam, maybe a friend would have to do that for the user or something if they are visually impaired, but perhaps considering adding a way to select a button (start/stop) just by using the keyboard? Great job, I really like this project!

**Comment by lmtaek** [comment]
Thanks for the feedback! 

You make a good point—currently, the buttons are accessible via click, or through screen-reading tools such as VoiceOver, though keyboard controls would definitely add another layer of usability. I'll try to add it in!

**Comment by lmtaek** [comment]
Hey! [I've added in keyboard functionality, so you can start or pause the audio by hitting the spacebar](https://github.com/lmtaek/pitchposition/commit/9b2afa14fcf48656c5b1fae0f756edd526829d8a). Thanks again for the suggestion! 

I'm still investigating accessibility in allowing access to a webcam, but I will close this issue due to its primary concern (using start/stop functions without clicking the buttons) being addressed.
